Adding new army json
tom3q/hex pull request #4
Opened 2019-09-09 20:16 UTC by mpolakow

Added new army - Outpost.json the last human army 
Modified json schema to include new abilities and modifiers

2019-09-10 15:53 UTC, tom3q requested changes

2019-09-10 15:53 UTC, tom3q commented on src/resources/armies/army.schema.json
> +		    "sniper"
Please keep them sorted alphabetically.

2019-09-10 15:53 UTC, tom3q commented on src/resources/armies/army.schema.json
> +		    "recon"
Ditto.

2019-09-10 15:54 UTC, tom3q commented on src/resources/armies/army.schema.json
> +		    "sniper"
Uh, and fix the tabs again...

2019-09-11 03:43 UTC, Nucleoprotein commented
Maybe use .editorconfig? ( https://editorconfig.org/ )

2019-09-11 04:01 UTC, tom3q commented
> Maybe use .editorconfig? ( https://editorconfig.org/ )

Sounds like a good idea. I'll check it in the evening.

2019-09-12 21:17 UTC, mpolakow commented on src/resources/armies/army.schema.json
> +		    "sniper"
Fixed

2019-09-12 21:17 UTC, mpolakow commented on src/resources/armies/army.schema.json
> +		    "recon"
Fixed

2019-09-13 03:35 UTC, tom3q commented
Please rebase.

2019-09-13 09:53 UTC, merged